#!/usr/bin/env bash
# installing Nginx and it should be listening on port 80

#make sure you are update and then install nginx
sudo apt-get update -y && \
         sudo apt-get upgrade -y
sudo apt-get install -y nginx

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

#redirect me to this video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=ciHrbMNf8XI&list=PLL1UEcDHVPjkGyNpXH4Ep4QPXkVDJNetL permanent;' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart
