#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get -y update
sudo apt -y install haproxy
sudo ufw allow 80/tcp
sudo service haproxy start
echo "ENABLED=1" >> /etc/default/haproxy

echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 483293-web-01 54.87.171.64:80 check
    server 483293-web-02 52.3.255.208:80 check
" >> /etc/haproxy/haproxy.cfg
sudo systemctl enable haproxy
sudo systemctl restart haproxy
