#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get -y update
sudo apt -y install haproxy
sudo ufw allow 80/tcp
sudo service haproxy start
config="\nfrontend alx_frontend\n\tbind *:80\n\tdefault_backend alx_backend\n"
config2="\nbackend alx_backend\n\tbalance roundrobin\n\tserver 483293-web-01 54.87.171.64:80 check\n\tserver 483293-web-02 52.3.255.208:80 check\n"
sudo sed -i "/504.http/ a\\${config}${config2}" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
